#pragma once

#include <redasm/redasm.h>

typedef enum {
    PE_CLASS_NONE = 0,
    PE_CLASS_MINGW,
    PE_CLASS_VISUAL_BASIC_5,
    PE_CLASS_VISUAL_BASIC_6,
    PE_CLASS_VISUAL_STUDIO_4,
    PE_CLASS_VISUAL_STUDIO_5,
    PE_CLASS_VISUAL_STUDIO_6,
    PE_CLASS_VISUAL_STUDIO_2002,
    PE_CLASS_VISUAL_STUDIO_2003,
    PE_CLASS_VISUAL_STUDIO_2005,
    PE_CLASS_VISUAL_STUDIO_2008,
    PE_CLASS_VISUAL_STUDIO_2010,
    PE_CLASS_VISUAL_STUDIO_2012,
    PE_CLASS_VISUAL_STUDIO_2013,
    PE_CLASS_VISUAL_STUDIO_2015,
    PE_CLASS_VISUAL_STUDIO_2017,
    PE_CLASS_DOTNET_1,
    PE_CLASS_DOTNET_2_X,
    PE_CLASS_BORLAND_DELPHI,
    PE_CLASS_BORLAND_DELPHI_3,
    PE_CLASS_BORLAND_DELPHI_6,
    PE_CLASS_BORLAND_DELPHI_7,
    PE_CLASS_BORLAND_DELPHI_9,
    PE_CLASS_BORLAND_DELPHI_10,
    PE_CLASS_BORLAND_DELPHI_XE,
    PE_CLASS_BORLAND_DELPHI_XE2_6,
    PE_CLASS_BORLAND_CPP,
} PEClassification;

typedef struct PEFormat PEFormat;

PEClassification pe_classify(const PEFormat* pe, RDContext* ctx);
void pe_classify_print(PEClassification c);
