#pragma once

// https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format

// Signatures
#define PE_NT_OPTIONAL_HDR32_MAGIC 0x10b
#define PE_NT_OPTIONAL_HDR64_MAGIC 0x20b
#define PE_ROM_OPTIONAL_HDR_MAGIC 0x107

// File Header
#define PE_FILE_MACHINE_ARM 0x1c0
#define PE_FILE_MACHINE_ARMNT 0x1c4 // Windows on ARM (aka Windows RT)
#define PE_FILE_MACHINE_AMD64 0x8664
#define PE_FILE_MACHINE_I386 0x14c

// Sections
#define PE_SIZE_OF_SHORT_NAME 8

#define PE_SCN_MEM_DISCARDABLE 0x02000000
#define PE_SCN_MEM_EXECUTE 0x20000000
#define PE_SCN_MEM_READ 0x40000000
#define PE_SCN_MEM_WRITE 0x80000000

#define PE_SCN_CNT_CODE 0x00000020
#define PE_SCN_CNT_INITIALIZED_DATA 0x00000040
#define PE_SCN_CNT_UNINITIALIZED_DATA 0x00000080

// Data Directory
#define PE_NUMBER_OF_DIRECTORY_ENTRIES 16

#define PE_DIRECTORY_ENTRY_EXPORT 0
#define PE_DIRECTORY_ENTRY_IMPORT 1
#define PE_DIRECTORY_ENTRY_RESOURCE 2
#define PE_DIRECTORY_ENTRY_EXCEPTION 3
#define PE_DIRECTORY_ENTRY_SECURITY 4
#define PE_DIRECTORY_ENTRY_BASERELOC 5
#define PE_DIRECTORY_ENTRY_DEBUG 6
#define PE_DIRECTORY_ENTRY_ARCHITECTURE 7
#define PE_DIRECTORY_ENTRY_GLOBALPTR 8
#define PE_DIRECTORY_ENTRY_TLS 9
#define PE_DIRECTORY_ENTRY_LOAD_CONFIG 10
#define PE_DIRECTORY_ENTRY_BOUND_IMPORT 11
#define PE_DIRECTORY_ENTRY_IAT 12
#define PE_DIRECTORY_ENTRY_DELAY_IMPORT 13
#define PE_DIRECTORY_ENTRY_COM_DESCRIPTOR 14
#define PE_DIRECTORY_ENTRY_DOTNET PE_DIRECTORY_ENTRY_COM_DESCRIPTOR
